config/routes.rb
Utilization::Application.routes.draw do
  resources :expertises

  resources :patronages

  resources :characteristics do
    member do
      get :patrons
    end
  end

  resources :details

  resources :aspirations

  resources :possessions

  resources :appreciations

  devise_for :users do
    match '/log_in' => 'devise/sessions#new', :as => 'log_in'
    match '/log_out' => 'devise/sessions#destroy', :as => 'log_out'
  end
  
  resources :users, :only => :show

  resources :things do
    member do
      get :owners
      get :appreciators
      get :aspiring_users
      get :experts
    end
  end
  
  match '/connect' => 'facebook#login'
  
  root :to => 'things#index'
  
  

end

app/models/characteristic.rb
class Characteristic < ActiveRecord::Base
  belongs_to :detail
  belongs_to :thing
  has_many :patronages
  has_many :users, :through => :patronages
  
  attr_accessor :detail_text
  before_create :grab_detail
  
  validates_uniqueness_of :detail_id, :scope => :thing_id
  
  def grab_detail
    self.detail = Detail.find_or_create_by_text detail_text if detail_text.present?
  end
  
  def find_or_save
    detail = Detail.where(:text => detail_text).first
    c = Characteristic.where(:detail_id => detail.id, :thing_id => thing_id).first if detail
    c ? c : save && self
  end
end

app/controllers/characteristics_controller.rb
class CharacteristicsController < ApplicationController
  def patrons
    @characteristic = Characteristic.find params[:id]
    @users = @characteristic.users
    render :action => 'users/index'
  end

  # GET /characteristics
  # GET /characteristics.json
  def index
    @characteristics = Characteristic.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @characteristics }
    end
  end

  # GET /characteristics/1
  # GET /characteristics/1.json
  def show
    @characteristic = Characteristic.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @characteristic }
    end
  end

  # GET /characteristics/new
  # GET /characteristics/new.json
  def new
    @characteristic = Characteristic.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @characteristic }
    end
  end

  # GET /characteristics/1/edit
  def edit
    @characteristic = Characteristic.find(params[:id])
  end

  # POST /characteristics
  # POST /characteristics.json
  def create
    @characteristic = Characteristic.new(params[:characteristic])

    respond_to do |format|
      if @characteristic.save
        format.html { redirect_to @characteristic, notice: 'Characteristic was successfully created.' }
        format.json { render json: @characteristic, status: :created, location: @characteristic }
      else
        format.html { render action: "new" }
        format.json { render json: @characteristic.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /characteristics/1
  # PUT /characteristics/1.json
  def update
    @characteristic = Characteristic.find(params[:id])

    respond_to do |format|
      if @characteristic.update_attributes(params[:characteristic])
        format.html { redirect_to @characteristic, notice: 'Characteristic was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @characteristic.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /characteristics/1
  # DELETE /characteristics/1.json
  def destroy
    @characteristic = Characteristic.find(params[:id])
    @characteristic.destroy

    respond_to do |format|
      format.html { redirect_to characteristics_url }
      format.json { head :ok }
    end
  end
end

app/helpers/characteristics_helper.rb
module CharacteristicsHelper
end

app/views/characteristics/_form.html.erb
<%= form_for(@characteristic) do |f| %>
  <% if @characteristic.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@characteristic.errors.count, "error") %> prohibited this characteristic from being saved:</h2>

      <ul>
      <% @characteristic.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :detail %><br />
    <%= f.text_field :detail %>
  </div>
  <div class="field">
    <%= f.label :thing %><br />
    <%= f.text_field :thing %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/characteristics/edit.html.erb
<h1>Editing characteristic</h1>

<%= render 'form' %>

<%= link_to 'Show', @characteristic %> |
<%= link_to 'Back', characteristics_path %>

app/views/characteristics/index.html.erb
<h1>Listing characteristics</h1>

<table>
  <tr>
    <th>Detail</th>
    <th>Thing</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @characteristics.each do |characteristic| %>
  <tr>
    <td><%= characteristic.detail %></td>
    <td><%= characteristic.thing %></td>
    <td><%= link_to 'Show', characteristic %></td>
    <td><%= link_to 'Edit', edit_characteristic_path(characteristic) %></td>
    <td><%= link_to 'Destroy', characteristic, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Characteristic', new_characteristic_path %>

app/views/characteristics/new.html.erb
<h1>New characteristic</h1>

<%= render 'form' %>

<%= link_to 'Back', characteristics_path %>

app/views/characteristics/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Detail:</b>
  <%= @characteristic.detail %>
</p>

<p>
  <b>Thing:</b>
  <%= @characteristic.thing %>
</p>


<%= link_to 'Edit', edit_characteristic_path(@characteristic) %> |
<%= link_to 'Back', characteristics_path %>