config/routes.rb
Utilization::Application.routes.draw do
  resources :expertises

  resources :patronages

  resources :characteristics do
    member do
      get :patrons
    end
  end

  resources :details

  resources :aspirations

  resources :possessions

  resources :appreciations

  devise_for :users do
    match '/log_in' => 'devise/sessions#new', :as => 'log_in'
    match '/log_out' => 'devise/sessions#destroy', :as => 'log_out'
  end
  
  resources :users, :only => :show

  resources :things do
    member do
      get :owners
      get :appreciators
      get :aspiring_users
      get :experts
    end
  end
  
  match '/connect' => 'facebook#login'
  
  root :to => 'things#index'
  
  

end

app/models/thing.rb
class Thing < ActiveRecord::Base
  belongs_to :user
  has_many :characteristics
  has_many :details, :through => :characteristics
  has_many :patronages, :through => :characteristics
  has_many :appreciations
  has_many :aspirations
  has_many :possessions
  has_many :expertises
  has_many :appreciators, :through => :appreciations, :source => :user
  has_many :owners, :through => :possessions, :source => :user
  has_many :aspiring_users, :through => :aspirations, :source => :user
  has_many :experts, :through => :expertises, :source => :user
  
  scope :alphabetical, order('name')
  scope :newest, order('created_at desc')
  scope :by_user, order('user_id desc')
  scope :shuffled, order('random()')
end

app/controllers/things_controller.rb
class ThingsController < ApplicationController
  before_filter :get_thing, :get_users, :only => [:owners, :appreciators, :aspiring_users, :experts]
  after_filter :friend_ids, :your_city, :only => [:owners, :appreciators, :aspiring_users, :experts]
  
  def owners
    render :action => 'users/index'
  end
  
  def appreciators
    render :action => 'users/index'
  end
  
  def aspiring_users
    render :action => 'users/index'
  end
  
  def experts
    render :action => 'users/index'
  end
  
  # GET /things
  # GET /things.json
  def index
    @things = if params[:sort].present?
      Thing.send params[:sort]
    else
      Thing.shuffled
    end.page(params[:page])

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @things }
      format.js
    end
  end

  # GET /things/1
  # GET /things/1.json
  def show
    @thing = Thing.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @thing }
    end
  end

  # GET /things/new
  # GET /things/new.json
  def new
    @thing = Thing.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @thing }
    end
  end

  # GET /things/1/edit
  def edit
    @thing = Thing.find(params[:id])
  end

  # POST /things
  # POST /things.json
  def create
    params[:thing][:user_id] ||= current_user.andand.id
    @thing = Thing.new(params[:thing])
    
    unless params[:overruled]
      @existing_thing = Thing.find_by_name(@thing.name)
    
      if @existing_thing
        render(:action => 'existing_thing') && return
      end
    end

    respond_to do |format|
      if @thing.save
        format.js
        format.html { redirect_to @thing, notice: 'Ready for action.' }
        format.json { render json: @thing, status: :created, location: @thing }
      else
        format.html { render action: "new" }
        format.json { render json: @thing.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /things/1
  # PUT /things/1.json
  def update
    @thing = Thing.find(params[:id])

    respond_to do |format|
      if @thing.update_attributes(params[:thing])
        format.html { redirect_to @thing, notice: 'Thing was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @thing.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /things/1
  # DELETE /things/1.json
  def destroy
    @thing = Thing.find(params[:id])
    @thing.destroy

    respond_to do |format|
      format.html { redirect_to things_url }
      format.json { head :ok }
    end
  end
  
  protected
  
  def friend_ids
    if current_facebook_user
      @friend_ids = current_facebook_user.friends.map(&:id)
      @users.sort_by { |u| @friend_ids.include? u.facebook_id }
    end
  end
  
  def your_city
    if current_user.andand.city.present?
      @users.sort_by { |u| @friend_ids.include?(u.facebook_id) || current_user.city == u.city }
    end
  end
  
  def get_thing
    @thing = Thing.find params[:id]
  end
  
  def get_users
    @users = @thing.send(params[:action])
  end
end

app/helpers/things_helper.rb
module ThingsHelper
end

app/views/things/_form.html.erb
<%= form_for(@thing) do |f| %>
  <% if @thing.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@thing.errors.count, "error") %> prohibited this thing from being saved:</h2>

      <ul>
      <% @thing.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :make %><br />
    <%= f.text_field :make %>
  </div>
  <div class="field">
    <%= f.label :photo_url %><br />
    <%= f.text_field :photo_url %>
  </div>
  <div class="field">
    <%= f.label :url %><br />
    <%= f.text_field :url %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description, :size => '28x4' %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
  <%= hidden_field_tag :overruled, :value => @overruled %>
<% end %>

app/views/things/_thing.html.erb
<li>
  <%= link_to thing.name, thing %>
  <div class='actions'>
    <% if current_user %>
      <%= link_to 'k', expertises_path(:expertise => {:user_id => current_user.id, :thing_id => thing.id}), :method => :post, :remote => true, :id => 'expertise_link', :class => 'action', :title => 'I know how to use this' unless current_user.is_expert_on?(thing) %>
    
      <%= link_to 'i', appreciations_path(:appreciation => {:user_id => current_user.id, :thing_id => thing.id}), :method => :post, :remote => true, :id => 'appreciate_link', :class => 'action', :title => 'I am interested' unless current_user.appreciates?(thing) %>

      <%= link_to 'h', possessions_path(:possession => {:user_id => current_user.id, :thing_id => thing.id}), :method => :post, :remote => true, :id => 'possess_link', :class => 'action', :title => 'I have one' unless current_user.possesses?(thing) %>

      <%= link_to 't', aspirations_path(:aspiration => {:user_id => current_user.id, :thing_id => thing.id}), :method => :post, :remote => true, :id => 'aspire_link', :class => 'action', :title => 'I want to try it' unless current_user.aspires_to_use?(thing) %>
    <% end %>
  </div>
</li>

app/views/things/create.js.erb
$('ul.list').prepend('<%= escape_javascript render(@thing) %>');
$('#thing_name').val('');

app/views/things/edit.html.erb
<h1>Editing thing</h1>

<%= render 'form' %>

<%= link_to 'Show', @thing %> |
<%= link_to 'Back', things_path %>

app/views/things/existing_thing.html.erb
There is already a thing called <%= link_to @existing_thing.name, @existing_thing %>.  If you want to make another, you can!  Here are the other details we have about this thing:

<% if @existing_thing.make.present? %>
  <div>
    made by: <%= @existing_thing.make %>
  </div>
<% end %>

<% if @existing_thing.description.present? %>
  <div>
    <%= @existing_thing.description %>
  </div>
<% end %>

<% if @existing_thing.photo_url.present? %>
  <div>
    <%= image_tag @existing_thing.photo_url %>
  </div>
<% end %>

<% if @existing_thing.url.present? %>
  <div>
    <%= link_to @existing_thing.url, @existing_thing.url %>
  </div>
<% end %>

<% if @existing_thing.details.present? %>
  Additional details:
  <ul>
    <% @existing_thing.details.each do |detail| %>
      <li><%= detail.text %></li>
    <% end %>
  </ul>
<% end %>

<div id='rollup'>
  <span><%= link_to(pluralize(@existing_thing.appreciations.count, 'person') + (@existing_thing.appreciations.count == 1 ? ' appreciates' : ' appreciate') + ' this.', appreciators_thing_path(@existing_thing)) %></span>
  <span><%= link_to(pluralize(@existing_thing.possessions.count, 'person') + (@existing_thing.possessions.count == 1 ? ' has' : ' have') + ' one.', owners_thing_path(@existing_thing)) %></span>
  <span><%= link_to(pluralize(@existing_thing.aspirations.count, 'person') + ' would like to use it.', aspiring_users_thing_path(@existing_thing)) %></span>
</div>

To continue with creating a new thing, just use this form.
<% @overruled = true %>
<%= render 'form' %>

app/views/things/index.html.erb
<h1>
  Here's some things.
</h1>

<%= link_to_function 'New Thing', "$('#new_thing').submit()", :class => 'new-button' %>
<%= form_for Thing.new do |f| %>
  <%= f.text_field :name %>
<% end %>

<ul class='sort'>
  <span>Sorting:</span>
  <li><%= link_to 'alphabetical', {:sort => 'alphabetical'} %></li>
  <li><%= link_to 'newest', {:sort => 'newest'} %></li>
  <li><%= link_to 'by user', {:sort => 'by_user'} %></li>
  <li><%= link_to 'random', {:sort => nil} %></li>
</ul>

<ul class='things list clearfix'>
	<%= render @things %>
</ul>
<br />
<%= paginate @things, :remote => true %>

app/views/things/index.js.erb
$('.things').html('<%= escape_javascript(render @things) %>');
$('.pagination').html('<%= escape_javascript(paginate @things, :remote => true) %>');

app/views/things/new.html.erb
<h1>New thing</h1>

<%= form_for(@thing) do |f| %>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>


<%= link_to 'Back', things_path %>

app/views/things/show.html.erb
<p id="notice"><%= notice %></p>

<h1><%= @thing.name %></h1>

<div id='actions'>
  <% if current_user %>
    <% if current_user.appreciates?(@thing) %>
      <span>You appreciate <%= @thing.name.pluralize %>.</span>
    <% else %>
      <%= link_to 'I appreciate ' + @thing.name.pluralize + '.', appreciations_path(:appreciation => {:user_id => current_user.id, :thing_id => @thing.id}), :method => :post, :remote => true, :id => 'appreciate_link', :class => 'action' %>
    <% end %>

    <% if current_user.possesses?(@thing) %>
      <span>You possess a <%= @thing.name %>.</span>
    <% else %>
      <%= link_to 'I possess a ' + @thing.name + '.', possessions_path(:possession => {:user_id => current_user.id, :thing_id => @thing.id}), :method => :post, :remote => true, :id => 'possess_link', :class => 'action' %>
    <% end %>
  
    <% if current_user.aspires_to_use?(@thing) %>
     <span>You would like to use a <%= @thing.name %>.</span>
    <% else %>
      <%= link_to 'I want to use a ' + @thing.name + '.', aspirations_path(:aspiration => {:user_id => current_user.id, :thing_id => @thing.id}), :method => :post, :remote => true, :id => 'aspire_link', :class => 'action' %>
    <% end %>
    
    <% if current_user.is_expert_on?(@thing) %>
     <span>You know how to use a <%= @thing.name %>.</span>
    <% else %>
      <%= link_to 'I know how to use a ' + @thing.name + '.', expertises_path(:expertise => {:user_id => current_user.id, :thing_id => @thing.id}), :method => :post, :remote => true, :id => 'expertise_link', :class => 'action' %>
    <% end %>
    
  <% end %>
</div>

<div class='rollup'>
	<label>You're not alone</label>
	<ul>
		<li><%= link_to(pluralize(@thing.appreciations.count, 'person') + (@thing.appreciations.count == 1 ? ' appreciates' : ' appreciate') + ' ' + @thing.name.pluralize + '.', appreciators_thing_path(@thing)) %></li>
		<li><%= link_to(pluralize(@thing.possessions.count, 'person') + (@thing.possessions.count == 1 ? ' has a ' + @thing.name + '.' : ' have ' + @thing.name.pluralize + '.'), owners_thing_path(@thing)) %></li>
		<li><%= link_to(pluralize(@thing.owners.count, 'person') + ' would like to use a ' + @thing.name + '.', aspiring_users_thing_path(@thing)) %></li>
		<li><%= link_to(pluralize(@thing.expertises.count, 'person') + (@thing.expertises.count == 1 ? ' knows' : ' know') + ' how to use a ' + @thing.name + '.', experts_thing_path(@thing)) %></li>
	</ul>
</div>		

<p>
  <%= @thing.make if @thing.make.present? %>
</p>
<p>
  <%= image_tag @thing.photo_url if @thing.photo_url.present? %>
</p>
<p>
  <%= link_to @thing.url, @thing.url if @thing.url.present? %>
</p>
<hr>
<p>
  <%= @thing.description %>
</p>

<% if @thing.details.present? %>
  <ul>
    <% @thing.characteristics.each do |characteristic| %>
      <li>
        <%= characteristic.detail.text %>
        <%= link_to pluralize(Patronage.where(:characteristic_id => characteristic).count, 'person') + (Patronage.where(:characteristic_id => characteristic).count == 1 ? ' thinks' : ' think') + ' so.', patrons_characteristic_path(characteristic) %>
        <%= link_to "and I agree!", patronages_path(:patronage => {:characteristic_id => characteristic.id, :user_id => current_user.id}), :method => :post, :remote => true unless !current_user || Patronage.where(:user_id => current_user.id, :characteristic_id => characteristic.id).present? %>
      </li>
    <% end %>
  </ul>
<% end %>


<%= link_to "Edit #{@thing.name}", edit_thing_path(@thing) if @thing.user == current_user %>

<%= content_for :fb_og_meta_tags do %> 
  <meta property="og:type" content="<%= Facebooker2.instance_variable_get('@namespace') %>:thing" /> 
  <meta property="og:title" content="<%= @thing.name %>" /> 
  <meta property="og:image" content="<%= @thing.photo_url.present? ? @thing.photo_url : 'http://school.discoveryeducation.com/clipart/images/backpack.gif'%>" /> 
  <meta property="og:description" content="<%= @thing.description.present? ? @thing.description : @thing.name %>" />
  <meta property="og:url" content="<%= thing_url @thing %>">
<% end %>