config/routes.rb
Utilization::Application.routes.draw do
  resources :expertises

  resources :patronages

  resources :characteristics do
    member do
      get :patrons
    end
  end

  resources :details

  resources :aspirations

  resources :possessions

  resources :appreciations

  devise_for :users do
    match '/log_in' => 'devise/sessions#new', :as => 'log_in'
    match '/log_out' => 'devise/sessions#destroy', :as => 'log_out'
  end
  
  resources :users, :only => :show

  resources :things do
    member do
      get :owners
      get :appreciators
      get :aspiring_users
      get :experts
    end
  end
  
  match '/connect' => 'facebook#login'
  
  root :to => 'things#index'
  
  

end

app/models/patronage.rb
class Patronage < ActiveRecord::Base
  belongs_to :characteristic
  belongs_to :user
  
  validates_uniqueness_of :characteristic_id, :scope => :user_id
  
  def detail
    characteristic.detail
  end
  
  scope :by_user, lambda { |user_id| where :user_id => user_id }
end

app/controllers/patronages_controller.rb
class PatronagesController < ApplicationController
  before_filter :authenticate_user!, :only => :create
  # GET /patronages
  # GET /patronages.json
  def index
    @patronages = Patronage.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @patronages }
    end
  end

  # GET /patronages/1
  # GET /patronages/1.json
  def show
    @patronage = Patronage.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @patronage }
    end
  end

  # GET /patronages/new
  # GET /patronages/new.json
  def new
    @patronage = Patronage.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @patronage }
    end
  end

  # GET /patronages/1/edit
  def edit
    @patronage = Patronage.find(params[:id])
  end

  # POST /patronages
  # POST /patronages.json
  def create
    unless params[:patronage].present?
      @characteristic = Characteristic.new :thing_id => params[:thing_id]
      @characteristic.detail_text = params[:detail_text]
      @characteristic = @characteristic.find_or_save
      params[:patronage] = {:characteristic_id => @characteristic.id, :user_id => current_user.id}
    end
    @patronage = Patronage.new(params[:patronage])

    respond_to do |format|
      if @patronage.save
        format.js
        format.html { redirect_to @patronage, notice: 'Patronage was successfully created.' }
        format.json { render json: @patronage, status: :created, location: @patronage }
      else
        format.html { render action: "new" }
        format.json { render json: @patronage.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /patronages/1
  # PUT /patronages/1.json
  def update
    @patronage = Patronage.find(params[:id])

    respond_to do |format|
      if @patronage.update_attributes(params[:patronage])
        format.html { redirect_to @patronage, notice: 'Patronage was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @patronage.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /patronages/1
  # DELETE /patronages/1.json
  def destroy
    @patronage = Patronage.find(params[:id])
    @patronage.destroy

    respond_to do |format|
      format.html { redirect_to patronages_url }
      format.json { head :ok }
    end
  end
end

app/helpers/patronages_helper.rb
module PatronagesHelper
end

app/views/patronages/_form.html.erb
<%= form_for(@patronage) do |f| %>
  <% if @patronage.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@patronage.errors.count, "error") %> prohibited this patronage from being saved:</h2>

      <ul>
      <% @patronage.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :characteristic %><br />
    <%= f.text_field :characteristic %>
  </div>
  <div class="field">
    <%= f.label :user %><br />
    <%= f.text_field :user %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/patronages/create.js.erb
$('#<%= dom_id(@patronage.characteristic.thing, :details_on) %>').prepend('<li><%= params[:detail_text] %></li>');

app/views/patronages/edit.html.erb
<h1>Editing patronage</h1>

<%= render 'form' %>

<%= link_to 'Show', @patronage %> |
<%= link_to 'Back', patronages_path %>

app/views/patronages/index.html.erb
<h1>Listing patronages</h1>

<table>
  <tr>
    <th>Characteristic</th>
    <th>User</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @patronages.each do |patronage| %>
  <tr>
    <td><%= patronage.characteristic %></td>
    <td><%= patronage.user %></td>
    <td><%= link_to 'Show', patronage %></td>
    <td><%= link_to 'Edit', edit_patronage_path(patronage) %></td>
    <td><%= link_to 'Destroy', patronage, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Patronage', new_patronage_path %>

app/views/patronages/new.html.erb
<h1>New patronage</h1>

<%= render 'form' %>

<%= link_to 'Back', patronages_path %>

app/views/patronages/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Characteristic:</b>
  <%= @patronage.characteristic %>
</p>

<p>
  <b>User:</b>
  <%= @patronage.user %>
</p>


<%= link_to 'Edit', edit_patronage_path(@patronage) %> |
<%= link_to 'Back', patronages_path %>